### ISSUE TITLE
Where might one go for community help with Raven?

### ISSUE THREAD

**Issue by MostHated** [kamranayub/kamranayub.github.io#21]
Hey there,
    I was wondering if you might be able to point me in the direction of where to find other Raven users in which I can ask questions? I am having an issue in which I believe maybe I am not going about using a session.Query correctly, but I am just not sure. I keep getting System.FormatException: Input string was not in a correct format, so I am trying to find somewhere I can get some help with it.

Thanks in advance!

**Comment by kamranayub** [comment]
Hey! I'd recommend asking on the Google Group and mention you're new to Raven. If you can provide the code snippet for context I think that'll help too. If you post a link here, I can take a look and try to help too! https://groups.google.com/forum/#!forum/ravendb

**Comment by MostHated** [comment]
Hey there, 
   Thanks for the reply. I had made a post over there in regards to getting Raven working with the Unity3d game engine, but only one gentleman had replied to any of the messages and I hate to keep bothering him. I was not sure where else to try, so I posted in the C# section of reddit and was lucky enough to get a reply with a fairly reasonable idea to try which I am going to try this morning if I can find the time. 

   While the code snippit is not very long, the information that goes along with it (and the error message, lol) are fairly long. I can go ahead and post it here if you care to take a look, I would definitely appreciate that! I will give the suggestion the person in the link tried and see how that works. If you happen to have any suggestions as well, that would be greatly appreciated! Im fairly new to C# (about 6 months or so) and have only been working with Raven for about a month. 90% of that time was spent trying to get it to work with Unity3d, though.

https://www.reddit.com/r/csharp/comments/8g4duf/need_some_help_getting_ravendb_4x_to_work_with_my/

**Comment by MostHated** [comment]
Just an update, the nice folks at Raven are going to take a look at my actual game server project within Unity to see if they can stop anything that might be wrong on their end. If that is not good support, especially for a community version, I don't know what is! A few fellas on the reddit post gave some good suggestions, but unfortunately, they all ended up with the same result. I am certainly no expert but it sure seems like it should be working. : /

**Comment by MostHated** [comment]
Update - I got it all worked out! It took quite a bit of work, but it finally loaded up data into my game.

**Comment by MostHated** [comment]
Yes and no, it became something that required some custom deserialization because of the fact that a lot of things in my game use enum/byte in order to keep network message size to a minimum, but because of that the default deserialization setup wasn't liking it. I had the choice of changing it in the receiving class or doing some deserialization work. It was a lot easier to do that as there was a lot more code changes that would have to be done by changing the Types of the items that were in the DB.

I am sure it would have been probably a quick and easy for many, but I have only been at this for 6 months or so, and only been working with Raven for 2 weeks or so. So there was a whole lot of learning that had to be done, lol. It came out fairly well though. I will have to see if I can consolidate it somehow, make it a bit more efficient. 

I just went and made one of these fellas for each thing in the DB that needed it in order to be read. I am sure there is a better way to go about it than having a ton of those, I was more worried about making sure it was actually going to work, lol.

`    public class TypeByteConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType)
        {
            throw new NotImplementedException();
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            var enumString = (string)reader.Value;

            return (byte)Enum.Parse(typeof(NpcType), enumString, true);
        }


        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }
    }`

**Comment by kamranayub** [comment]
Oh yeah! This is technically more of a JSON.NET thing since Raven uses that
for serialization but yes, I've run into similar issues with serialization
formatting. Glad you got it worked out! This might warrant a contribution
to the Raven docs on custom type serialization so people are aware.

**Comment by MostHated** [comment]
Yeah, definitely not a bad idea. : )
